// Code generated by go-swagger; DO NOT EDIT.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutProviderHandlerFunc turns a function with the right signature into a put provider handler
type PutProviderHandlerFunc func(PutProviderParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutProviderHandlerFunc) Handle(params PutProviderParams) middleware.Responder {
	return fn(params)
}

// PutProviderHandler interface for that can handle valid put provider params
type PutProviderHandler interface {
	Handle(PutProviderParams) middleware.Responder
}

// NewPutProvider creates a new http.Handler for the put provider operation
func NewPutProvider(ctx *middleware.Context, handler PutProviderHandler) *PutProvider {
	return &PutProvider{Context: ctx, Handler: handler}
}

/* PutProvider swagger:route PUT /provider Provider putProvider

Health check

Health check endpoint

*/
type PutProvider struct {
	Context *middleware.Context
	Handler PutProviderHandler
}

func (o *PutProvider) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutProviderParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutProviderBody put provider body
//
// swagger:model PutProviderBody
type PutProviderBody struct {

	// id
	ID string `json:"id,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this put provider body
func (o *PutProviderBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put provider body based on context it is used
func (o *PutProviderBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutProviderBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutProviderBody) UnmarshalBinary(b []byte) error {
	var res PutProviderBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PutProviderOKBody put provider o k body
//
// swagger:model PutProviderOKBody
type PutProviderOKBody struct {

	// response code
	ResponseCode string `json:"response_code,omitempty"`

	// response data
	ResponseData string `json:"response_data,omitempty"`

	// response messege
	ResponseMessege string `json:"response_messege,omitempty"`
}

// Validate validates this put provider o k body
func (o *PutProviderOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put provider o k body based on context it is used
func (o *PutProviderOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutProviderOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutProviderOKBody) UnmarshalBinary(b []byte) error {
	var res PutProviderOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
