swagger: "2.0"
info:
  version: "1.0.0"
  title: "Sms Microservive"
  description: "Sms Microservive"
host: "localhost:8080"

schemes:
  - "http"

securityDefinitions:  
   Bearer:    
     type: apiKey    
     name: Authorization    
     in: header

tags:
  - name: "Health"
    description: "Every request and response about Health Check"
  - name: "Auth"
    description: "Every request and response about Auth"

paths:
  /redirect:
    get:
      summary: "Health check"
      description: "Health check endpoint"
      tags:
        - "Health"
      produces:
        - "application/json"
      parameters:
        - name: access_token
          type: string
          in: query
          description: Tags to filter by
          required: true
      responses:
        "200":
          description: "Success"
          schema:
            type: object
            properties:
              access_token:
                type: "string"
                description: "success retrieve data"
                example: "app running well"
        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/BadRequest"
        "404":
          $ref: "#/responses/NotFound"  
  /welcome:
    get:
      summary: "Health check"
      description: "Health check endpoint"
      tags:
        - "Health"
      produces:
        - "application/json"
      security:
       - Bearer: []
      responses:
        "200":
          description: "Success"
          schema:
            type: object
            properties:
              message:
                type: "string"
                description: "success retrieve data"
                example: "app running well"
        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/BadRequest"
        "404":
          $ref: "#/responses/NotFound"
  /create-otp:
    post:
      summary: "Add a new pet to the store"
      description: "Health check endpoint"
      tags:
        - "Auth"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          type: object
          properties: 
            phone_number:
              type: string
              description: "user phone_number"
              example: "081334702936"
      responses:
        "200":
          description: "Success"
          schema:
            type: object
            properties:
              message:
                type: "string"
                description: "success retrieve data"
                example: "Success"
              data:
                type: object
                properties: 
                  otp:
                    type: string
                    description: "user otp"
                    example: "123456"
        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/BadRequest"
        "404":
          $ref: "#/responses/NotFound"
  /validate-otp:
    post:
      summary: "Add a new pet to the store"
      description: "Health check endpoint"
      tags:
        - "Auth"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          type: object
          properties: 
            phone_number:
              type: string
              description: "user phone_number"
              example: "081334702936"
            otp:
              type: string
              description: "user otp"
              example: "123456"
      responses:
        "200":
          description: "Success"
          schema:
            type: object
            properties:
              message:
                type: "string"
                description: "success retrieve data"
                example: "Success"
              data:
                type: object
                properties: 
                  user:
                    type: string
                    description: "user otp"
                    example: "081334702936"
                  access_token:
                    type: string
                    description: "user otp"
                    example: ""
        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/BadRequest"
        "404":
          $ref: "#/responses/NotFound"
definitions:
  MakingPayment:
        type: array
        items: 
          type: object
          properties: 
            header:
              type: string
              example: ""
            description:
              type: string
              example: ""


  Health:
    type: "object"
    properties:
      status:
        type: string
        example: "Good"
  
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
        example: "error"

responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/Error"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"

  BadRequest:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"

  InternalServerError:
    description: Internal server error
    schema:
      $ref: "#/definitions/Error"
