// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"hanoman-id/xendit-payment/internal/apis/operations/provider"
	"hanoman-id/xendit-payment/internal/apis/operations/sms"
	"hanoman-id/xendit-payment/internal/apis/operations/template"
)

// NewSmsMicroserviceAPI creates a new SmsMicroservice instance
func NewSmsMicroserviceAPI(spec *loads.Document) *SmsMicroserviceAPI {
	return &SmsMicroserviceAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		TemplateDeleteTemplateTemplateIDHandler: template.DeleteTemplateTemplateIDHandlerFunc(func(params template.DeleteTemplateTemplateIDParams) middleware.Responder {
			return middleware.NotImplemented("operation template.DeleteTemplateTemplateID has not yet been implemented")
		}),
		ProviderGetProviderHandler: provider.GetProviderHandlerFunc(func(params provider.GetProviderParams) middleware.Responder {
			return middleware.NotImplemented("operation provider.GetProvider has not yet been implemented")
		}),
		SmsGetSmsHistoryHandler: sms.GetSmsHistoryHandlerFunc(func(params sms.GetSmsHistoryParams) middleware.Responder {
			return middleware.NotImplemented("operation sms.GetSmsHistory has not yet been implemented")
		}),
		TemplateGetTemplateHandler: template.GetTemplateHandlerFunc(func(params template.GetTemplateParams) middleware.Responder {
			return middleware.NotImplemented("operation template.GetTemplate has not yet been implemented")
		}),
		SmsPostSmsHandler: sms.PostSmsHandlerFunc(func(params sms.PostSmsParams) middleware.Responder {
			return middleware.NotImplemented("operation sms.PostSms has not yet been implemented")
		}),
		TemplatePostTemplateHandler: template.PostTemplateHandlerFunc(func(params template.PostTemplateParams) middleware.Responder {
			return middleware.NotImplemented("operation template.PostTemplate has not yet been implemented")
		}),
		ProviderPutProviderHandler: provider.PutProviderHandlerFunc(func(params provider.PutProviderParams) middleware.Responder {
			return middleware.NotImplemented("operation provider.PutProvider has not yet been implemented")
		}),
		TemplatePutTemplateTemplateIDHandler: template.PutTemplateTemplateIDHandlerFunc(func(params template.PutTemplateTemplateIDParams) middleware.Responder {
			return middleware.NotImplemented("operation template.PutTemplateTemplateID has not yet been implemented")
		}),
	}
}

/*SmsMicroserviceAPI Sms Microservive */
type SmsMicroserviceAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// TemplateDeleteTemplateTemplateIDHandler sets the operation handler for the delete template template ID operation
	TemplateDeleteTemplateTemplateIDHandler template.DeleteTemplateTemplateIDHandler
	// ProviderGetProviderHandler sets the operation handler for the get provider operation
	ProviderGetProviderHandler provider.GetProviderHandler
	// SmsGetSmsHistoryHandler sets the operation handler for the get sms history operation
	SmsGetSmsHistoryHandler sms.GetSmsHistoryHandler
	// TemplateGetTemplateHandler sets the operation handler for the get template operation
	TemplateGetTemplateHandler template.GetTemplateHandler
	// SmsPostSmsHandler sets the operation handler for the post sms operation
	SmsPostSmsHandler sms.PostSmsHandler
	// TemplatePostTemplateHandler sets the operation handler for the post template operation
	TemplatePostTemplateHandler template.PostTemplateHandler
	// ProviderPutProviderHandler sets the operation handler for the put provider operation
	ProviderPutProviderHandler provider.PutProviderHandler
	// TemplatePutTemplateTemplateIDHandler sets the operation handler for the put template template ID operation
	TemplatePutTemplateTemplateIDHandler template.PutTemplateTemplateIDHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *SmsMicroserviceAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *SmsMicroserviceAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *SmsMicroserviceAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SmsMicroserviceAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SmsMicroserviceAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SmsMicroserviceAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SmsMicroserviceAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SmsMicroserviceAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SmsMicroserviceAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SmsMicroserviceAPI
func (o *SmsMicroserviceAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.TemplateDeleteTemplateTemplateIDHandler == nil {
		unregistered = append(unregistered, "template.DeleteTemplateTemplateIDHandler")
	}
	if o.ProviderGetProviderHandler == nil {
		unregistered = append(unregistered, "provider.GetProviderHandler")
	}
	if o.SmsGetSmsHistoryHandler == nil {
		unregistered = append(unregistered, "sms.GetSmsHistoryHandler")
	}
	if o.TemplateGetTemplateHandler == nil {
		unregistered = append(unregistered, "template.GetTemplateHandler")
	}
	if o.SmsPostSmsHandler == nil {
		unregistered = append(unregistered, "sms.PostSmsHandler")
	}
	if o.TemplatePostTemplateHandler == nil {
		unregistered = append(unregistered, "template.PostTemplateHandler")
	}
	if o.ProviderPutProviderHandler == nil {
		unregistered = append(unregistered, "provider.PutProviderHandler")
	}
	if o.TemplatePutTemplateTemplateIDHandler == nil {
		unregistered = append(unregistered, "template.PutTemplateTemplateIDHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SmsMicroserviceAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SmsMicroserviceAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *SmsMicroserviceAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *SmsMicroserviceAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *SmsMicroserviceAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SmsMicroserviceAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the sms microservice API
func (o *SmsMicroserviceAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SmsMicroserviceAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/template/{template_id}"] = template.NewDeleteTemplateTemplateID(o.context, o.TemplateDeleteTemplateTemplateIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/provider"] = provider.NewGetProvider(o.context, o.ProviderGetProviderHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/sms/history"] = sms.NewGetSmsHistory(o.context, o.SmsGetSmsHistoryHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/template"] = template.NewGetTemplate(o.context, o.TemplateGetTemplateHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/sms"] = sms.NewPostSms(o.context, o.SmsPostSmsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/template"] = template.NewPostTemplate(o.context, o.TemplatePostTemplateHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/provider"] = provider.NewPutProvider(o.context, o.ProviderPutProviderHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/template/{template_id}"] = template.NewPutTemplateTemplateID(o.context, o.TemplatePutTemplateTemplateIDHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SmsMicroserviceAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SmsMicroserviceAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SmsMicroserviceAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SmsMicroserviceAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *SmsMicroserviceAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
