// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateTemplate create template
//
// swagger:model CreateTemplate
type CreateTemplate struct {

	// apps name
	AppsName string `json:"apps_name,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// text
	Text string `json:"text,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this create template
func (m *CreateTemplate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create template based on context it is used
func (m *CreateTemplate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateTemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTemplate) UnmarshalBinary(b []byte) error {
	var res CreateTemplate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
