// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateSmsRequest create sms request
//
// swagger:model CreateSmsRequest
type CreateSmsRequest struct {

	// apps name
	AppsName string `json:"apps_name,omitempty"`

	// phone number
	PhoneNumber string `json:"phone_number,omitempty"`

	// token
	Token string `json:"token,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this create sms request
func (m *CreateSmsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create sms request based on context it is used
func (m *CreateSmsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSmsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSmsRequest) UnmarshalBinary(b []byte) error {
	var res CreateSmsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
