// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SmsResponse sms response
//
// swagger:model SmsResponse
type SmsResponse struct {

	// apps name
	AppsName string `json:"apps_name,omitempty"`

	// phone number
	PhoneNumber string `json:"phone_number,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this sms response
func (m *SmsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sms response based on context it is used
func (m *SmsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SmsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SmsResponse) UnmarshalBinary(b []byte) error {
	var res SmsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
