// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package query

import (
	"database/sql"
)

type Provider struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	IsSelected sql.NullBool `json:"is_selected"`
	IsDeleted  sql.NullBool `json:"is_deleted"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type SmsHistory struct {
	ID          string       `json:"id"`
	Sender      string       `json:"sender"`
	PhoneNumber string       `json:"phone_number"`
	Type        string       `json:"type"`
	Status      string       `json:"status"`
	IsDeleted   bool         `json:"is_deleted"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Template struct {
	ID        string       `json:"id"`
	Type      string       `json:"type"`
	AppsName  string       `json:"apps_name"`
	Text      string       `json:"text"`
	IsDeleted sql.NullBool `json:"is_deleted"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID        string       `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	IsDeleted sql.NullBool `json:"is_deleted"`
	CreatedAt sql.NullTime `json:"created_at"`
}
