// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package query

import ()

type MakingPayment struct {
	ID          int32  `json:"id"`
	BankCode    string `json:"bank_code"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

type Otp struct {
	ID          int32  `json:"id"`
	PhoneNumber string `json:"phone_number"`
	Otp         string `json:"otp"`
	ExpiredDate string `json:"expired_date"`
}
