// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package query

import ()

type MakingPayment struct {
	ID              int32  `json:"id"`
	BankCode        string `json:"bank_code"`
	Atm             string `json:"atm"`
	InternetBanking string `json:"internet_banking"`
	MobileBanking   string `json:"mobile_banking"`
}
