// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: provider.sql

package query

import (
	"context"
)

const getProvider = `-- name: GetProvider :one
SELECT
    id,
    name
FROM
    provider
WHERE
    id = "1"
    and is_deleted = false
`

type GetProviderRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetProvider(ctx context.Context) (*GetProviderRow, error) {
	row := q.db.QueryRowContext(ctx, getProvider)
	var i GetProviderRow
	err := row.Scan(&i.ID, &i.Name)
	return &i, err
}

const updateProvider = `-- name: UpdateProvider :exec
UPDATE
    provider
SET
    name = ?
WHERE
    id = "1"
    and is_deleted = false
`

func (q *Queries) UpdateProvider(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, updateProvider, name)
	return err
}
