// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: user.sql

package query

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT
    username,
    password
FROM
    users
WHERE
    username = ?
    and is_deleted = false
`

type GetUserRow struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) GetUser(ctx context.Context, username string) (*GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(&i.Username, &i.Password)
	return &i, err
}
