// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTemplateTemplateIDParams creates a new DeleteTemplateTemplateIDParams object
//
// There are no default values defined in the spec.
func NewDeleteTemplateTemplateIDParams() DeleteTemplateTemplateIDParams {

	return DeleteTemplateTemplateIDParams{}
}

// DeleteTemplateTemplateIDParams contains all the bound params for the delete template template ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteTemplateTemplateID
type DeleteTemplateTemplateIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	TemplateID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteTemplateTemplateIDParams() beforehand.
func (o *DeleteTemplateTemplateIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTemplateID, rhkTemplateID, _ := route.Params.GetOK("template_id")
	if err := o.bindTemplateID(rTemplateID, rhkTemplateID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTemplateID binds and validates parameter TemplateID from path.
func (o *DeleteTemplateTemplateIDParams) bindTemplateID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.TemplateID = raw

	return nil
}
