// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteTemplateTemplateIDHandlerFunc turns a function with the right signature into a delete template template ID handler
type DeleteTemplateTemplateIDHandlerFunc func(DeleteTemplateTemplateIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTemplateTemplateIDHandlerFunc) Handle(params DeleteTemplateTemplateIDParams) middleware.Responder {
	return fn(params)
}

// DeleteTemplateTemplateIDHandler interface for that can handle valid delete template template ID params
type DeleteTemplateTemplateIDHandler interface {
	Handle(DeleteTemplateTemplateIDParams) middleware.Responder
}

// NewDeleteTemplateTemplateID creates a new http.Handler for the delete template template ID operation
func NewDeleteTemplateTemplateID(ctx *middleware.Context, handler DeleteTemplateTemplateIDHandler) *DeleteTemplateTemplateID {
	return &DeleteTemplateTemplateID{Context: ctx, Handler: handler}
}

/* DeleteTemplateTemplateID swagger:route DELETE /template/{template_id} Template deleteTemplateTemplateId

Health check

Health check endpoint

*/
type DeleteTemplateTemplateID struct {
	Context *middleware.Context
	Handler DeleteTemplateTemplateIDHandler
}

func (o *DeleteTemplateTemplateID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteTemplateTemplateIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteTemplateTemplateIDOKBody delete template template ID o k body
//
// swagger:model DeleteTemplateTemplateIDOKBody
type DeleteTemplateTemplateIDOKBody struct {

	// response code
	ResponseCode string `json:"response_code,omitempty"`

	// response data
	ResponseData interface{} `json:"response_data,omitempty"`

	// response messege
	ResponseMessege string `json:"response_messege,omitempty"`
}

// Validate validates this delete template template ID o k body
func (o *DeleteTemplateTemplateIDOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete template template ID o k body based on context it is used
func (o *DeleteTemplateTemplateIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTemplateTemplateIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTemplateTemplateIDOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteTemplateTemplateIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
