// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"hanoman-id/xendit-payment/internal/models"
)

// GetTemplateOKCode is the HTTP code returned for type GetTemplateOK
const GetTemplateOKCode int = 200

/*GetTemplateOK Success

swagger:response getTemplateOK
*/
type GetTemplateOK struct {

	/*
	  In: Body
	*/
	Payload *GetTemplateOKBody `json:"body,omitempty"`
}

// NewGetTemplateOK creates GetTemplateOK with default headers values
func NewGetTemplateOK() *GetTemplateOK {

	return &GetTemplateOK{}
}

// WithPayload adds the payload to the get template o k response
func (o *GetTemplateOK) WithPayload(payload *GetTemplateOKBody) *GetTemplateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get template o k response
func (o *GetTemplateOK) SetPayload(payload *GetTemplateOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTemplateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTemplateBadRequestCode is the HTTP code returned for type GetTemplateBadRequest
const GetTemplateBadRequestCode int = 400

/*GetTemplateBadRequest Unauthorized

swagger:response getTemplateBadRequest
*/
type GetTemplateBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTemplateBadRequest creates GetTemplateBadRequest with default headers values
func NewGetTemplateBadRequest() *GetTemplateBadRequest {

	return &GetTemplateBadRequest{}
}

// WithPayload adds the payload to the get template bad request response
func (o *GetTemplateBadRequest) WithPayload(payload *models.Error) *GetTemplateBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get template bad request response
func (o *GetTemplateBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTemplateBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTemplateUnauthorizedCode is the HTTP code returned for type GetTemplateUnauthorized
const GetTemplateUnauthorizedCode int = 401

/*GetTemplateUnauthorized Unauthorized

swagger:response getTemplateUnauthorized
*/
type GetTemplateUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTemplateUnauthorized creates GetTemplateUnauthorized with default headers values
func NewGetTemplateUnauthorized() *GetTemplateUnauthorized {

	return &GetTemplateUnauthorized{}
}

// WithPayload adds the payload to the get template unauthorized response
func (o *GetTemplateUnauthorized) WithPayload(payload *models.Error) *GetTemplateUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get template unauthorized response
func (o *GetTemplateUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTemplateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTemplateNotFoundCode is the HTTP code returned for type GetTemplateNotFound
const GetTemplateNotFoundCode int = 404

/*GetTemplateNotFound The specified resource was not found

swagger:response getTemplateNotFound
*/
type GetTemplateNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTemplateNotFound creates GetTemplateNotFound with default headers values
func NewGetTemplateNotFound() *GetTemplateNotFound {

	return &GetTemplateNotFound{}
}

// WithPayload adds the payload to the get template not found response
func (o *GetTemplateNotFound) WithPayload(payload *models.Error) *GetTemplateNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get template not found response
func (o *GetTemplateNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTemplateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
