// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"hanoman-id/xendit-payment/internal/models"
)

// PutTemplateTemplateIDOKCode is the HTTP code returned for type PutTemplateTemplateIDOK
const PutTemplateTemplateIDOKCode int = 200

/*PutTemplateTemplateIDOK Success

swagger:response putTemplateTemplateIdOK
*/
type PutTemplateTemplateIDOK struct {

	/*
	  In: Body
	*/
	Payload *PutTemplateTemplateIDOKBody `json:"body,omitempty"`
}

// NewPutTemplateTemplateIDOK creates PutTemplateTemplateIDOK with default headers values
func NewPutTemplateTemplateIDOK() *PutTemplateTemplateIDOK {

	return &PutTemplateTemplateIDOK{}
}

// WithPayload adds the payload to the put template template Id o k response
func (o *PutTemplateTemplateIDOK) WithPayload(payload *PutTemplateTemplateIDOKBody) *PutTemplateTemplateIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put template template Id o k response
func (o *PutTemplateTemplateIDOK) SetPayload(payload *PutTemplateTemplateIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTemplateTemplateIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutTemplateTemplateIDBadRequestCode is the HTTP code returned for type PutTemplateTemplateIDBadRequest
const PutTemplateTemplateIDBadRequestCode int = 400

/*PutTemplateTemplateIDBadRequest Unauthorized

swagger:response putTemplateTemplateIdBadRequest
*/
type PutTemplateTemplateIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutTemplateTemplateIDBadRequest creates PutTemplateTemplateIDBadRequest with default headers values
func NewPutTemplateTemplateIDBadRequest() *PutTemplateTemplateIDBadRequest {

	return &PutTemplateTemplateIDBadRequest{}
}

// WithPayload adds the payload to the put template template Id bad request response
func (o *PutTemplateTemplateIDBadRequest) WithPayload(payload *models.Error) *PutTemplateTemplateIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put template template Id bad request response
func (o *PutTemplateTemplateIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTemplateTemplateIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutTemplateTemplateIDUnauthorizedCode is the HTTP code returned for type PutTemplateTemplateIDUnauthorized
const PutTemplateTemplateIDUnauthorizedCode int = 401

/*PutTemplateTemplateIDUnauthorized Unauthorized

swagger:response putTemplateTemplateIdUnauthorized
*/
type PutTemplateTemplateIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutTemplateTemplateIDUnauthorized creates PutTemplateTemplateIDUnauthorized with default headers values
func NewPutTemplateTemplateIDUnauthorized() *PutTemplateTemplateIDUnauthorized {

	return &PutTemplateTemplateIDUnauthorized{}
}

// WithPayload adds the payload to the put template template Id unauthorized response
func (o *PutTemplateTemplateIDUnauthorized) WithPayload(payload *models.Error) *PutTemplateTemplateIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put template template Id unauthorized response
func (o *PutTemplateTemplateIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTemplateTemplateIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutTemplateTemplateIDNotFoundCode is the HTTP code returned for type PutTemplateTemplateIDNotFound
const PutTemplateTemplateIDNotFoundCode int = 404

/*PutTemplateTemplateIDNotFound The specified resource was not found

swagger:response putTemplateTemplateIdNotFound
*/
type PutTemplateTemplateIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutTemplateTemplateIDNotFound creates PutTemplateTemplateIDNotFound with default headers values
func NewPutTemplateTemplateIDNotFound() *PutTemplateTemplateIDNotFound {

	return &PutTemplateTemplateIDNotFound{}
}

// WithPayload adds the payload to the put template template Id not found response
func (o *PutTemplateTemplateIDNotFound) WithPayload(payload *models.Error) *PutTemplateTemplateIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put template template Id not found response
func (o *PutTemplateTemplateIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTemplateTemplateIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
