CREATE TABLE IF NOT EXISTS otp (
    id INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    phone_number VARCHAR(100) NOT NULL UNIQUE,
    otp VARCHAR(10) NOT NULL,
    expired_date VARCHAR(100) NOT NULL
);