swagger: "2.0"
info:
  version: "1.0.0"
  title: "Hanoman Payment Xendit"
  description: "Hanoman Payment Xendit"
host: "virtserver.swaggerhub.com"

schemes:
  - "http"

tags:
  - name: "Health"
    description: "Every request and response about Health Check"
  - name: "Family"
    description: "Every request and response about Family"
  - name: "Me"
    description: "Every request and response about Me"

paths:
  
  /health:
    get:
      summary: "Health check"
      description: "Health check endpoint"
      tags:
        - "Health"
      produces:
        - "application/json"

      responses:
        "200":
          description: "Success"
          schema:
            type: object
            properties:
              message:
                type: "string"
                description: "success retrieve data"
                example: "app running well"
              data:
                type: object
                $ref: "#/definitions/Health"

        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/BadRequest"
        "404":
          $ref: "#/responses/NotFound"
  
definitions:
  
  Health:
    type: "object"
    properties:
      status:
        type: string
        example: "Good"
  
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
        example: "error"

responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/Error"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"

  BadRequest:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"

  InternalServerError:
    description: Internal server error
    schema:
      $ref: "#/definitions/Error"
