// Code generated by go-swagger; DO NOT EDIT.

package sms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"hanoman-id/xendit-payment/internal/models"
)

// GetSmsHistoryOKCode is the HTTP code returned for type GetSmsHistoryOK
const GetSmsHistoryOKCode int = 200

/*GetSmsHistoryOK Success

swagger:response getSmsHistoryOK
*/
type GetSmsHistoryOK struct {

	/*
	  In: Body
	*/
	Payload *GetSmsHistoryOKBody `json:"body,omitempty"`
}

// NewGetSmsHistoryOK creates GetSmsHistoryOK with default headers values
func NewGetSmsHistoryOK() *GetSmsHistoryOK {

	return &GetSmsHistoryOK{}
}

// WithPayload adds the payload to the get sms history o k response
func (o *GetSmsHistoryOK) WithPayload(payload *GetSmsHistoryOKBody) *GetSmsHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sms history o k response
func (o *GetSmsHistoryOK) SetPayload(payload *GetSmsHistoryOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSmsHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSmsHistoryBadRequestCode is the HTTP code returned for type GetSmsHistoryBadRequest
const GetSmsHistoryBadRequestCode int = 400

/*GetSmsHistoryBadRequest Unauthorized

swagger:response getSmsHistoryBadRequest
*/
type GetSmsHistoryBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSmsHistoryBadRequest creates GetSmsHistoryBadRequest with default headers values
func NewGetSmsHistoryBadRequest() *GetSmsHistoryBadRequest {

	return &GetSmsHistoryBadRequest{}
}

// WithPayload adds the payload to the get sms history bad request response
func (o *GetSmsHistoryBadRequest) WithPayload(payload *models.Error) *GetSmsHistoryBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sms history bad request response
func (o *GetSmsHistoryBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSmsHistoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSmsHistoryUnauthorizedCode is the HTTP code returned for type GetSmsHistoryUnauthorized
const GetSmsHistoryUnauthorizedCode int = 401

/*GetSmsHistoryUnauthorized Unauthorized

swagger:response getSmsHistoryUnauthorized
*/
type GetSmsHistoryUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSmsHistoryUnauthorized creates GetSmsHistoryUnauthorized with default headers values
func NewGetSmsHistoryUnauthorized() *GetSmsHistoryUnauthorized {

	return &GetSmsHistoryUnauthorized{}
}

// WithPayload adds the payload to the get sms history unauthorized response
func (o *GetSmsHistoryUnauthorized) WithPayload(payload *models.Error) *GetSmsHistoryUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sms history unauthorized response
func (o *GetSmsHistoryUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSmsHistoryUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSmsHistoryNotFoundCode is the HTTP code returned for type GetSmsHistoryNotFound
const GetSmsHistoryNotFoundCode int = 404

/*GetSmsHistoryNotFound The specified resource was not found

swagger:response getSmsHistoryNotFound
*/
type GetSmsHistoryNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSmsHistoryNotFound creates GetSmsHistoryNotFound with default headers values
func NewGetSmsHistoryNotFound() *GetSmsHistoryNotFound {

	return &GetSmsHistoryNotFound{}
}

// WithPayload adds the payload to the get sms history not found response
func (o *GetSmsHistoryNotFound) WithPayload(payload *models.Error) *GetSmsHistoryNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sms history not found response
func (o *GetSmsHistoryNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSmsHistoryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
